### ISSUE TITLE
events.js:183 - Error: ESPIPE: invalid seek, read

### ISSUE THREAD

**Issue by MrSponti** [song940/input-event#11]
I try to use **'input-event'** under node v8.11.1 and get the following error:

```
$ node -v
v8.11.1
$ getinput.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ESPIPE: invalid seek, read
```
Any idea how to solve this issue?

**Comment by mrdago** [comment]
Ok, I solved the issue by cloning the git repository. 
```
$ npm install input-event --save
``` 
will not load the latest version including the armv6l workaround in _'lib/index.js'_.

In case that I load the modul from the git repository every thing is working as expected.
```
    "dependencies": {
        "input-event": "github:song940/input-event",,
        ...
```

**Comment by adamreisnz** [comment]
Experiencing the same error, using the code from master fixed it. When is this going to be released to npm??

**Comment by lsongdev** [comment]
input-event@1.2.4 published @adamreisnz
