### ISSUE TITLE
Error: ENODEV: no such device, read

### ISSUE THREAD

**Issue by adamreisnz** [song940/input-event#14]
Is it possible for this error not to crash the Node app but emit the error event, so that we can gracefully handle this error without it crashing the whole app?

This happens when for example the device is disconnected/unplugged.

**Comment by davidatingenuity** [comment]
I am experiencing the same issue - when an input device is removed, the keyboard.on('error') handler is not always called, and even when it is, node crashes with an 'Unhandled error event' exception:
```
        input = new InputEvent(options.barcodeScannerPath);
        keyboard = new InputEvent.Keyboard(input);
        keyboard.on('keyup', processKeyEvent);    
        keyboard.on('keypress', processKeyEvent);    
        keyboard.on('keydown', processKeyEvent); 
        keyboard.on('error', processErrorEvent);

....

function processErrorEvent(error) {
  console.log('Error Event', error);
}

```


On disconnection of the input device (a barcode scanner), the following is printed, then node exits:

```
Error Event { Error: ENODEV: no such device, read errno: -19, code: 'ENODEV', syscall: 'read' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENODEV: no such device, read
```

Changing the name of the event emitted from 'error' to 'disconnect' allows me to handle the disconnection event without node crashing. See 9b611ab55bd8650354ca428490e61440ba41d63a.

**Comment by leonardo-k** [comment]
i think we can close this issue after commit 5f9a0ef, rigth?

**Comment by lsongdev** [comment]
@leonardo-k yep
