### ISSUE TITLE
Linux only? ENOENT: no such file or directory, open '/dev/input/event0'

### ISSUE THREAD

**Issue by frankhale** [song940/input-event#15]
I needed a module for global key handling and ran across this but it doesn't seem to work on Windows and there isn't anything mentioned that says what OSes it supports. Since there is a reference to kernel.org I suspect it's only for Linux but am not sure. 

```
Uncaught Error: ENOENT: no such file or directory, open '/dev/input/event0'
```

**Comment by lsongdev** [comment]
Linux only.

**Comment by frankhale** [comment]
Do you mind putting something in the readme that says this? Would help others like me so they don't waste time.

**Comment by frankhale** [comment]
Why does your screenshot show a Windows machine if this is Linux only?

### Showcase

![](https://raw.githubusercontent.com/song940/input-event/master/example/ir-remote.jpg)
