### ISSUE TITLE
Windows Usage Instruction

### ISSUE THREAD

**Issue by Levertion** [song940/input-event#7]
How do I get the path needed for my devices in Windows? I think it might be related to `HID\VID_046D&PID_C31C&MI_00\7&1585C721&0&0000`
as explained [here](https://www.silabs.com/community/interface/knowledge-base.entry.html/2013/11/21/windows_usb_devicep-aGxD), but I'm not sure how to get it to connect. I tried:
```javascript
const InputEvent = require("input-event");
var input = new InputEvent("HID\\VID_046D&PID_C31C&MI_00\\7&1585C721&0&0000");
```
But this gives an error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'c:\Users\Levertion\Documents\Other Code\ahk_replace_test\HID\VID_046D&PID_C31C&MI_00\7&1585C721&0&0000'
    at Error (native)
```
By placing breakpoints I can see that the index.js function runs successfully, however, I cannot work out where the exception actually occurs.
I think that this should be usable in windows based on your screenshot, which shows it working on what looks like Windows 7 - if it doesn't work in Windows I'm sorry for wasting your time
Edit is due to accidental use of keyboard shortcut to send issue before it was complete

**Comment by lsongdev** [comment]
only linux, does not supports windows, never.

**Comment by Levertion** [comment]
Maybe an explanation of this literally anywhere would be good, and not having an image in the readme which suggests fairly explicitly that it works on windows. I suspected that it didn't support windows, but this still needs an explanation.
